# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deployment

on:
  push:
    tags:
    - 'v*'

jobs:
  build-job:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        package_manager: [npm, yarn]

    steps:
    - name: Check out Git repository
      uses: actions/checkout@v3

    - name: Use Node.js 14
      uses: actions/setup-node@v3
      with:
        node-version: 14.x
        cache: 'yarn'
    
    - name: Install Dependencies
      run: ${{ matrix.package_manager }} install
    
    - name: Build
      run: ${{ matrix.package_manager }} electron:build
      
    - name: Win build  
      run: ${{ matrix.package_manager }} electron:win-build

  deploy-job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - run: export GH_TOKEN=${{ secrets.GITHUB_TOKEN }} && ${{ matrix.package_manager }} electron:release
    - run: export GH_TOKEN=${{ secrets.GITHUB_TOKEN }} && ${{ matrix.package_manager }} electron:win-release