# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deployment

on:
  push:
    tags:
      - "v*"

jobs:
  macBuildAndRelease:
    strategy:
      matrix:
        os: [macos-latest]
        # os: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Use Node.js 14
        uses: actions/setup-node@v3
        with:
          node-version: 14.x

      - name: Make .env file
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_AUTH_PRIVATEKEY: ${{secrets.AUTH_PRIVATEKEY}}
          envkey_AUTH_INSIDEDEVELOPERUSERGROUP_ARRAY: ${{secrets.AUTH_INSIDEDEVELOPERUSERGROUP_ARRAY}}
          envkey_AUTH_INSIDEPASSWORD: ${{secrets.AUTH_INSIDEPASSWORD}}
          envkey_AUTH_INSIDEPMUSERGROUP_ARRAY: ${{secrets.AUTH_INSIDEPMUSERGROUP_ARRAY}}
          envkey_JENKINS_BASEURL: ${{secrets.JENKINS_BASEURL}}
          envkey_JENKINS_USERNAME: ${{secrets.JENKINS_USERNAME}}
          envkey_JENKINS_PASSWORD: ${{secrets.JENKINS_PASSWORD}}
          envkey_GITLAB_HOST: ${{secrets.GITLAB_HOST}}
          envkey_GITLAB_BASEURL: ${{secrets.GITLAB_BASEURL}}
          envkey_GITLAB_USERNAME: ${{secrets.GITLAB_USERNAME}}
          envkey_GITLAB_PASSWORD: ${{secrets.GITLAB_PASSWORD}}
          envkey_GITLAB_PRIVATE_TOKEN: ${{secrets.GITLAB_PRIVATE_TOKEN}}
          envkey_SONARQUBE_SERVER: ${{secrets.SONARQUBE_SERVER}}
          envkey_SONARQUBE_USERNAME: ${{secrets.SONARQUBE_USERNAME}}
          envkey_SONARQUBE_PASSWORD: ${{secrets.SONARQUBE_PASSWORD}}
          envkey_SONARQUBE_TOKEN: ${{secrets.SONARQUBE_TOKEN}}
          envkey_ALIYUN_REGIONID: ${{secrets.ALIYUN_REGIONID}}
          envkey_ALIYUN_ACCESSKEYID: ${{secrets.ALIYUN_ACCESSKEYID}}
          envkey_ALIYUN_ACCESSKEYSECRET: ${{secrets.ALIYUN_ACCESSKEYSECRET}}
          envkey_DEF_MAIL_ADDRESSEE: ${{secrets.DEF_MAIL_ADDRESSEE}}
          envkey_DEF_MAIL_SENDER_USER: ${{secrets.DEF_MAIL_SENDER_USER}}
          envkey_DEF_MAIL_SENDER_PASS: ${{secrets.DEF_MAIL_SENDER_PASS}}
          envkey_PMLIST_ARRAY: ${{secrets.PMLIST_ARRAY}}
          envkey_ENVTYPES_ARRAY: ${{secrets.ENVTYPES_ARRAY}}
          directory: env
          file_name: .env
          fail_on_empty: false

      - name: Install Dependencies
        run: yarn install

      - name: Build
        run: yarn electron:build

      - name: Release
        run: yarn electron:release

  winBuildAndRelease:
    strategy:
      matrix:
        os: [macos-latest]

    runs-on: ${{ matrix.os }}

    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Use Node.js 14
        uses: actions/setup-node@v3
        with:
          node-version: 14.x

      - name: Make .env file
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_AUTH_PRIVATEKEY: ${{secrets.AUTH_PRIVATEKEY}}
          envkey_AUTH_INSIDEDEVELOPERUSERGROUP_ARRAY: ${{secrets.AUTH_INSIDEDEVELOPERUSERGROUP_ARRAY}}
          envkey_AUTH_INSIDEPASSWORD: ${{secrets.AUTH_INSIDEPASSWORD}}
          envkey_AUTH_INSIDEPMUSERGROUP_ARRAY: ${{secrets.AUTH_INSIDEPMUSERGROUP_ARRAY}}
          envkey_JENKINS_BASEURL: ${{secrets.JENKINS_BASEURL}}
          envkey_JENKINS_USERNAME: ${{secrets.JENKINS_USERNAME}}
          envkey_JENKINS_PASSWORD: ${{secrets.JENKINS_PASSWORD}}
          envkey_GITLAB_HOST: ${{secrets.GITLAB_HOST}}
          envkey_GITLAB_BASEURL: ${{secrets.GITLAB_BASEURL}}
          envkey_GITLAB_USERNAME: ${{secrets.GITLAB_USERNAME}}
          envkey_GITLAB_PASSWORD: ${{secrets.GITLAB_PASSWORD}}
          envkey_GITLAB_PRIVATE_TOKEN: ${{secrets.GITLAB_PRIVATE_TOKEN}}
          envkey_SONARQUBE_SERVER: ${{secrets.SONARQUBE_SERVER}}
          envkey_SONARQUBE_USERNAME: ${{secrets.SONARQUBE_USERNAME}}
          envkey_SONARQUBE_PASSWORD: ${{secrets.SONARQUBE_PASSWORD}}
          envkey_SONARQUBE_TOKEN: ${{secrets.SONARQUBE_TOKEN}}
          envkey_ALIYUN_REGIONID: ${{secrets.ALIYUN_REGIONID}}
          envkey_ALIYUN_ACCESSKEYID: ${{secrets.ALIYUN_ACCESSKEYID}}
          envkey_ALIYUN_ACCESSKEYSECRET: ${{secrets.ALIYUN_ACCESSKEYSECRET}}
          envkey_DEF_MAIL_ADDRESSEE: ${{secrets.DEF_MAIL_ADDRESSEE}}
          envkey_DEF_MAIL_SENDER_USER: ${{secrets.DEF_MAIL_SENDER_USER}}
          envkey_DEF_MAIL_SENDER_PASS: ${{secrets.DEF_MAIL_SENDER_PASS}}
          envkey_PMLIST_ARRAY: ${{secrets.PMLIST_ARRAY}}
          envkey_ENVTYPES_ARRAY: ${{secrets.ENVTYPES_ARRAY}}
          directory: env
          file_name: .env
          fail_on_empty: false

      - name: Install Dependencies
        run: yarn install

      - name: Build
        run: yarn electron:win-build

      - name: Release
        run: yarn electron:win-release
